# Generated by Django 3.2.3 on 2021-05-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20210524_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markers',
            name='lat',
            field=models.DecimalField(decimal_places=20, max_digits=23),
        ),
        migrations.AlterField(
            model_name='markers',
            name='lng',
            field=models.DecimalField(decimal_places=20, max_digits=23),
        ),
    ]
