# Generated by Django 3.2.3 on 2021-05-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20210531_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markers',
            name='price',
            field=models.IntegerField(),
        ),
    ]
