# Generated by Django 3.2.3 on 2021-05-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_markers_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markers',
            name='lat',
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
        migrations.AlterField(
            model_name='markers',
            name='lng',
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
    ]
