# Generated by Django 3.2.3 on 2021-05-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
