# Generated by Django 3.2.3 on 2021-05-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_delete_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markers',
            name='owner',
        ),
    ]
