# Generated by Django 3.2.3 on 2021-05-26 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_markers_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='markers',
            unique_together={('lat', 'lng')},
        ),
    ]
