# Generated by Django 3.2.3 on 2021-05-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_alter_markers_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markers',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='markers',
            name='lng',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
